### ISSUE TITLE
gollm.SetOllamaEndpoint()

### ISSUE THREAD

**Issue by mogenleN** [teilomillet/gollm#1]
gollm.SetOllamaEndpoint()   This method is invalid.

**Comment by mogenleN** [comment]
It is suggested that you can customize the API

**Comment by teilomillet** [comment]
Hello @mogenleN thank you for your feedback !

I wanted to make it customizable to but forget to remove the hardcode.

The necessary change as been made, you can now use SetOllamaEndpoint(). It will use your the adresse of your choice and add the /api/generate to it.

I made a change in the examples/ollama_example.go too in order to show the change.
