### ISSUE TITLE
Is there anything I can do? 

### ISSUE THREAD

**Issue by jh2310** [teilomillet/gollm#3]

**Comment by jh2310** [comment]
gollm What is the essential difference between ollam and LangChain, and what are the advantages of existing projects? I think we need to find some differentiation，Otherwise, we're just copying functions that others already have.

**Comment by teilomillet** [comment]
You're absolutely right that it's crucial to have a clear differentiation and purpose. Let me explain how I've positioned gollm:

LangChain is built as a tool to build chatbots, while gollm is built as a tool for prompt engineering, focusing solely on the interaction with the LLM output (the response to a prompt).

You can see LangChain as a Swiss Army knife that can handle chat completion, but also RAG building, etc. You can basically do almost anything with a minimum for each tool. To me, LangChain's goal is to make it do a lot of things.

gollm, on the other hand, is like a commando knife that can handle prompt optimization, easy comparison of multiple LLM outputs, and mix of agents. You can get structured output with validation (even for open source models). The goal is to make that knife cut almost anything - the sharper, the better.

## My Experience and Encouragement

I want to be clear: LangChain is an excellent tool, and I encourage you to use it. I used LangChain extensively for over a year, and it's incredibly powerful and versatile. However, my frustrations with certain aspects of it led me to build gollm as a specialized tool to address my specific needs.

## Development Approach

My approach to developing gollm is strictly needs-based and organic. We don't add features simply because they exist in other packages like LangChain. Instead, we add functionality when there's a genuine need for it in our workflow or when community members identify a gap that gollm can uniquely fill.
For example:

- I needed a prompt optimization tool, so I added it to gollm.
- I needed structured output with validation that would work with whatever models I used, so I added it.
- When sammcj needed a Mix of Agents feature, he contributed it to the project.

This approach ensures that every feature in gollm serves a real, practical purpose and aligns with our focus on prompt engineering and LLM output handling.

If you want to help gollm grow and don't know where to start:

- Build something using gollm. Start simple – this could lead to great examples for the community.
- Add support for new LLM providers. This is always needed, and I'm planning to create a guide to make this process even easier.
- Explore the existing examples and try to extend them or create new ones based on your specific use cases.

Your real-world experiences and needs are what will drive gollm's evolution.

## Our Goal

I'm not aiming to replicate everything that LangChain or other libraries do. Instead, I'm building a highly specialized tool that excels at prompt engineering and LLM output handling. To use the knife analogy: I'm crafting an exceptionally sharp blade for cutting, not trying to add screwdrivers or scissors to our toolkit.

But remember, we are building a good knife, not a screwdriver or scissors or anything else.

**Comment by jh2310** [comment]
I understand your ideas and goals, so where should we start now, or what are the high-priority needs currently? I look forward to this project bringing great convenience to all developers and having stars like ollam and LangChain!

**Comment by teilomillet** [comment]
Build with gollm - this is our highest priority!

- What problem are you trying to solve?
- Create a simple example using gollm features
- Iterate and improve your project


Share your work:

- Add docs explaining what you did
- Post about your project on r/gollm
- Write a quick article or make a short video
- Tweet or share on dev forums



If you can create something that will help newcomers, that would be fantastic. Consider a beginner-friendly project or tutorial that showcases gollm's key features.
As you work, you'll likely come up with feature ideas or find bugs to report.
