### ISSUE TITLE
Claude caching

### ISSUE THREAD

**Issue by alehano** [teilomillet/gollm#9]
Does this package support Claude prompt caching? If so how to use it?

**Comment by teilomillet** [comment]
It does not yet, I might implement it later. What is your use case @alehano ?

**Comment by alehano** [comment]
I would like you to cache quite a long system prompt

**Comment by teilomillet** [comment]
I have made a change in the code so that we can use caching from Anthropic. 
Could you try it please ?

I put it in the branch "cache", to test it, before merging with the main.

There is an example in examples/caching_example.go that you should be able to understand how to use it.

I hope it works ! 
@alehano

**Comment by teilomillet** [comment]
Claude caching is up ! @alehano
